// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-YOmYDTYsA8-RUyx1M3B7ibPqNV6TYM',
    appId: '1:806424217561:web:328738a0662e425939bbc8',
    messagingSenderId: '806424217561',
    projectId: 'projecttr-1dda0',
    authDomain: 'projecttr-1dda0.firebaseapp.com',
    storageBucket: 'projecttr-1dda0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCle-GfAbmr2luV1FeZTVp7V8nqbtKU2AA',
    appId: '1:806424217561:android:c910eec4cd1708ce39bbc8',
    messagingSenderId: '806424217561',
    projectId: 'projecttr-1dda0',
    storageBucket: 'projecttr-1dda0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1gyzN8opKTszwi78vAzdU0CDgAXF3bA',
    appId: '1:806424217561:ios:117fc45b44e0203139bbc8',
    messagingSenderId: '806424217561',
    projectId: 'projecttr-1dda0',
    storageBucket: 'projecttr-1dda0.firebasestorage.app',
    iosClientId: '806424217561-g2j3l8njsfvtr2b78s1n4168uc6l89cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1gyzN8opKTszwi78vAzdU0CDgAXF3bA',
    appId: '1:806424217561:ios:117fc45b44e0203139bbc8',
    messagingSenderId: '806424217561',
    projectId: 'projecttr-1dda0',
    storageBucket: 'projecttr-1dda0.firebasestorage.app',
    iosClientId: '806424217561-g2j3l8njsfvtr2b78s1n4168uc6l89cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiX39NxxwfYMqvD_aASqGgbq2_BP1xClY',
    appId: '1:806424217561:web:feb0af158ad72e9c39bbc8',
    messagingSenderId: '806424217561',
    projectId: 'projecttr-1dda0',
    authDomain: 'projecttr-1dda0.firebaseapp.com',
    storageBucket: 'projecttr-1dda0.firebasestorage.app',
  );

}